name: generate-posters-and-build

on:
  push:
    paths:
      - 'public/videos/**'
      - 'scripts/**'
  workflow_dispatch: {}

jobs:
  posters-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: npm ci

      - name: Generate posters (choose best frame)
        # Use the heuristic to avoid black or uninformative first frames
        run: node ./scripts/generate-posters.js --update-manifest --best-frame

      - name: Build site
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist/
